name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set deploy path
        run: echo "DEPLOYPATH=/home/uwjwmvgdaply/public_html/repositories/equatorangular" >> $GITHUB_ENV

      - name: Copy files
        run: |
          f [ -d ".vscode" ]; then /bin/cp -R .vscode $DEPLOYPATH; fi
          if [ -d "assets" ]; then /bin/cp -R assets $DEPLOYPATH; fi
          if [ -d "css" ]; then /bin/cp -R css $DEPLOYPATH; fi
          if [ -d "fonts" ]; then /bin/cp -R fonts $DEPLOYPATH; fi
          if [ -d "img" ]; then /bin/cp -R img $DEPLOYPATH; fi
          if [ -d "js" ]; then /bin/cp -R js $DEPLOYPATH; fi
          if [ -f "test.html" ]; then /bin/cp test.html $DEPLOYPATH; fi
       shell: /usr/bin/bash -e {0}
       env:
          DEPLOYPATH: /home/uwjwmvgdaply/public_html/repositories/equatorangular
