name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set deploy path
        run: echo "DEPLOYPATH=/home/uwjwmvgdaply/public_html/repositories/equatorangular" >> $GITHUB_ENV

      - name: Copy files
        run: |
          /bin/cp -R .vscode $DEPLOYPATH
          /bin/cp -R assets $DEPLOYPATH
          /bin/cp -R css $DEPLOYPATH
          /bin/cp -R fonts $DEPLOYPATH
          /bin/cp -R img $DEPLOYPATH
          /bin/cp -R js $DEPLOYPATH
          /bin/cp test.html $DEPLOYPATH
